"""add suggested goals

Revision ID: a0b99eadd162
Revises: e6f6886a6c4f
Create Date: 2026-03-16 17:34:44.802861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b99eadd162'
down_revision: Union[str, Sequence[str], None] = 'e6f6886a6c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sessions', sa.Column('selected_goal_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'selected_goal_id')
    op.drop_table('suggested_goals')
    # ### end Alembic commands ###
